export const translations = {
  en: {
    nav: { solutions: "Solutions", howItWorks: "How It Works", contact: "Contact", signIn: "Sign In", getStarted: "Get Started" },
    hero: {
      badge: "Enterprise AI Automation",
      line1: "Your AI partner", line2: "for the next", line2accent: "decade",
      description: "ARP Solutions helps enterprises eliminate operational complexity through AI-powered automation ecosystems — so your team focuses on what drives growth.",
      cta1: "Get Started", cta2: "Watch Demo",
      stat1val: "Proven ROI", stat1lbl: "Across every engagement",
      stat2val: "Massive",   stat2lbl: "Hours saved per month",
      dashTitle: "AI Engine Active", dashLive: "Live", dashChart: "Weekly performance",
      dashSaved: "Time Saved", dashAcc: "Accuracy", dashUp: "Uptime",
      notifTitle: "New qualified lead captured", notifSub: "2 minutes ago · Automated",
    },
    services: {
      badge: "What we do",
      title: "Everything your enterprise needs", titleAccent: "to scale with AI",
      subtitle: "From your first automation to a fully integrated AI ecosystem — built for enterprises that refuse to stand still.",
      learnMore: "Learn more",
      items: [
        { tag: "Process Automation",  title: "AI Workflow Automation", desc: "Eliminate manual bottlenecks with end-to-end business process automation. ARP Solutions designs intelligent AI agents that learn your workflows and scale alongside your operations.", feats: ["Autonomous AI agents, 24/7", "End-to-end process coverage", "Zero disruption to existing ops"], metric: { val: "Massive", lbl: "reduction in manual workload" } },
        { tag: "Data Intelligence",   title: "Predictive Analytics",   desc: "Transform raw enterprise data into strategic advantage. Our models surface patterns, forecast outcomes, and raise proactive alerts before problems emerge.", feats: ["Real-time data dashboards", "Proactive anomaly alerts", "Custom forecasting models"], metric: { val: "[X]×", lbl: "improvement in forecast accuracy" } },
        { tag: "Customer Experience", title: "Conversational AI",      desc: "Deploy chatbots and AI Voice Agents that handle inbound calls, qualify leads, and resolve support tickets without human intervention.", feats: ["AI voice agents for phone calls", "Intelligent human escalation", "Omnichannel deployment"], metric: { val: "[X]%", lbl: "of inquiries resolved autonomously" } },
        { tag: "Infrastructure",      title: "API Integrations",        desc: "Connect AI capabilities with your existing enterprise tech stack — CRM, ERP, HRIS, and proprietary databases. Secure, enterprise-grade architecture.", feats: ["REST & GraphQL API support", "SSO & RBAC security", "99.9% uptime SLA"], metric: { val: "Rapid", lbl: "time-to-integration" } },
      ],
      ctaEyebrow: "Ready to transform your operations?", ctaTitle: "Start automating.", ctaAccent: "Scale without limits.", ctaBtn1: "Talk to our team", ctaBtn2: "Watch a live demo",
    },
    hiw: {
      badge: "Our process", title: "From first meeting to", titleAccent: "live AI systems",
      subtitle: "A proven four-phase methodology — from operational audit to a fully deployed, continuously improving AI ecosystem with zero disruption.",
      steps: [
        { phase: "Discovery",    title: "We audit your operations",    desc: "Our team audits your workflows, tech stack, and pain points — mapping every manual process and quantifying where time and revenue are being lost.", bullets: ["Current-state workflow mapping", "Tech stack & integration assessment", "Automation opportunity scoring"] },
        { phase: "Architecture", title: "We design your AI ecosystem", desc: "We architect a custom AI ecosystem — selecting the right models, designing agent logic, and planning every integration. No off-the-shelf templates.", bullets: ["Custom AI agent architecture", "End-to-end integration blueprint", "Phased rollout roadmap"] },
        { phase: "Deployment",   title: "We build and integrate",      desc: "Our engineers deploy your AI workflows, connect them via secure API integrations, and run rigorous testing before anything goes live.", bullets: ["Secure API & system integration", "Parallel testing environment", "Zero-downtime deployment"] },
        { phase: "Optimization", title: "We monitor and improve",      desc: "Post-launch, systems continuously monitor performance, flag anomalies, and self-optimize. You get a dashboard, reports, and direct access to our team.", bullets: ["Real-time performance monitoring", "Continuous model retraining", "Dedicated success partnership"] },
      ],
      trust: [
        { val: "Weeks, not months", lbl: "Average time to first deployment" },
        { val: "Zero downtime",     lbl: "Guaranteed deployment approach" },
        { val: "Continuous ROI",    lbl: "Post-launch optimization included" },
      ],
    },
    contact: {
      badge: "Contact us", title: "Let's build your", titleAccent: "AI ecosystem",
      subtitle: "Reach out directly to one of our founders, or fill out the form and we'll get back to you within one business day.",
      founders: "Reach a founder directly",
      formTitle: "Send us a message", formDesc: "Tell us about your project and we'll put together a tailored proposal within 24 hours.",
      name: "Full name", email: "Work email", company: "Company", service: "Service of interest", message: "Message",
      namePh: "Jane Smith", emailPh: "jane@company.com", companyPh: "Acme Corp", servicePh: "Select a service…", messagePh: "Tell us about your project and current challenges…",
      submit: "Send message", sending: "Sending…",
      privacy: "We typically respond within 1 business day. Your information is never shared.",
      successTitle: "Message sent!", successDesc: "Thanks for reaching out. One of the ARP Solutions founders will reply within one business day.", successBtn: "Send another message",
      errorMsg: "Something went wrong. Please try again or email us directly.",
      emails: [{ lbl: "General Inquiries", val: "hello@arpsolutions.ai" }, { lbl: "Enterprise Sales", val: "sales@arpsolutions.ai" }, { lbl: "Careers", val: "careers@arpsolutions.ai" }],
      services: ["AI Workflow Automation", "Predictive Analytics", "Conversational AI", "API Integrations", "General Inquiry"],
      founderPhone: "Phone",
    },
    footer: {
      ctaEyebrow: "Let's build together", ctaTitle: "Ready to deploy your", ctaAccent: "AI ecosystem?",
      ctaDesc: "Book a free discovery call with Justin, Alexander, or Adrian — and walk away with a clear AI roadmap for your enterprise.",
      ctaBtn1: "Book a discovery call", ctaBtn2: "Explore our services →",
      brandDesc: "Enterprise AI Automation Ecosystems. Founded by Justin Kuijper, Alexander Janssen, and Adrian Alvarez.",
      newsletter: "Stay in the loop", nlPh: "your@company.com", nlBtn: "Subscribe", nlSuccess: "You're subscribed. Welcome aboard.",
      colSolutions: "Solutions", colNavigate: "Navigate", colLegal: "Legal",
      navLinks: ["Home", "Solutions", "How It Works", "Contact"],
      legalLinks: ["Privacy Policy", "Terms of Service", "Cookie Policy", "Security"],
      rights: "All rights reserved.", status: "All systems operational",
    },
  },

  es: {
    nav: { solutions: "Soluciones", howItWorks: "Cómo funciona", contact: "Contacto", signIn: "Iniciar sesión", getStarted: "Empezar" },
    hero: {
      badge: "Automatización IA Empresarial",
      line1: "Tu aliado de IA", line2: "para la próxima", line2accent: "década",
      description: "ARP Solutions ayuda a empresas a eliminar la complejidad operativa con ecosistemas de automatización IA — para que tu equipo se enfoque en lo que impulsa el crecimiento.",
      cta1: "Empezar", cta2: "Ver demo",
      stat1val: "ROI Probado", stat1lbl: "En cada proyecto",
      stat2val: "Masivo", stat2lbl: "Horas ahorradas por mes",
      dashTitle: "Motor IA Activo", dashLive: "En vivo", dashChart: "Rendimiento semanal",
      dashSaved: "Ahorro", dashAcc: "Precisión", dashUp: "Uptime",
      notifTitle: "Nuevo lead cualificado capturado", notifSub: "Hace 2 minutos · Automatizado",
    },
    services: {
      badge: "Lo que hacemos",
      title: "Todo lo que necesita tu empresa", titleAccent: "para crecer con IA",
      subtitle: "Desde tu primera automatización hasta un ecosistema de IA completo — para empresas que no se detienen.",
      learnMore: "Saber más",
      items: [
        { tag: "Automatización", title: "Automatización de Flujos IA", desc: "Elimina los cuellos de botella manuales con automatización de procesos de extremo a extremo mediante agentes IA inteligentes.", feats: ["Agentes IA autónomos 24/7", "Cobertura completa del proceso", "Sin interrupción operativa"], metric: { val: "Masivo", lbl: "reducción de carga manual" } },
        { tag: "Inteligencia de Datos", title: "Analítica Predictiva", desc: "Transforma datos empresariales en ventaja competitiva. Nuestros modelos detectan patrones y emiten alertas proactivas.", feats: ["Dashboards en tiempo real", "Alertas de anomalías", "Modelos personalizados"], metric: { val: "[X]×", lbl: "mejora en precisión de pronóstico" } },
        { tag: "Experiencia Cliente", title: "IA Conversacional", desc: "Despliega chatbots y agentes de voz IA para gestionar llamadas, calificar leads y resolver tickets sin intervención humana.", feats: ["Agentes de voz para llamadas", "Escalado inteligente", "Despliegue omnicanal"], metric: { val: "[X]%", lbl: "consultas resueltas automáticamente" } },
        { tag: "Infraestructura", title: "Integraciones API", desc: "Conecta capacidades IA con tu stack tecnológico — CRM, ERP, HRIS y bases de datos propias con arquitectura segura.", feats: ["Soporte REST & GraphQL", "Seguridad SSO & RBAC", "SLA 99,9% uptime"], metric: { val: "Rápido", lbl: "tiempo hasta integración" } },
      ],
      ctaEyebrow: "¿Listo para transformar tus operaciones?", ctaTitle: "Empieza a automatizar.", ctaAccent: "Escala sin límites.", ctaBtn1: "Habla con nuestro equipo", ctaBtn2: "Ver demo en vivo",
    },
    hiw: {
      badge: "Nuestro proceso", title: "Del primer encuentro a", titleAccent: "sistemas IA en producción",
      subtitle: "Una metodología de cuatro fases — desde auditoría operativa hasta ecosistema IA desplegado, sin interrupciones.",
      steps: [
        { phase: "Descubrimiento", title: "Auditamos tus operaciones", desc: "Análisis profundo de tus flujos, stack tecnológico y puntos de dolor para cuantificar el tiempo y los ingresos perdidos.", bullets: ["Mapeo del estado actual", "Evaluación del stack tecnológico", "Puntuación de oportunidades"] },
        { phase: "Arquitectura", title: "Diseñamos tu ecosistema IA", desc: "Arquitecturamos un ecosistema IA totalmente personalizado, sin plantillas genéricas.", bullets: ["Arquitectura de agentes IA", "Blueprint de integración completo", "Hoja de ruta por fases"] },
        { phase: "Despliegue", title: "Construimos e integramos", desc: "Desplegamos los flujos IA con ciclos de prueba rigurosos antes de salir a producción.", bullets: ["Integración API segura", "Entorno de pruebas paralelo", "Despliegue sin inactividad"] },
        { phase: "Optimización", title: "Monitorizamos y mejoramos", desc: "Monitorizamos el rendimiento continuamente y auto-optimizamos, con dashboard dedicado y acceso directo al equipo.", bullets: ["Monitorización en tiempo real", "Reentrenamiento continuo", "Partnership de éxito dedicado"] },
      ],
      trust: [
        { val: "Semanas, no meses", lbl: "Tiempo hasta primer despliegue" },
        { val: "Cero inactividad", lbl: "Enfoque de despliegue garantizado" },
        { val: "ROI continuo", lbl: "Optimización post-lanzamiento incluida" },
      ],
    },
    contact: {
      badge: "Contáctanos", title: "Construyamos tu", titleAccent: "ecosistema IA",
      subtitle: "Contacta directamente con uno de nuestros fundadores, o rellena el formulario y te responderemos en un día laboral.",
      founders: "Contacta directamente con un fundador",
      formTitle: "Envíanos un mensaje", formDesc: "Cuéntanos tu proyecto y elaboraremos una propuesta personalizada en 24 horas.",
      name: "Nombre completo", email: "Email corporativo", company: "Empresa", service: "Servicio de interés", message: "Mensaje",
      namePh: "Ana García", emailPh: "ana@empresa.com", companyPh: "Mi Empresa", servicePh: "Selecciona un servicio…", messagePh: "Cuéntanos sobre tu proyecto y retos actuales…",
      submit: "Enviar mensaje", sending: "Enviando…",
      privacy: "Respondemos en menos de 1 día laboral. Tu información nunca se comparte.",
      successTitle: "¡Mensaje enviado!", successDesc: "Gracias por contactarnos. Uno de los fundadores de ARP Solutions te responderá en un día laboral.", successBtn: "Enviar otro mensaje",
      errorMsg: "Algo salió mal. Por favor inténtalo de nuevo o escríbenos directamente.",
      emails: [{ lbl: "Consultas generales", val: "hello@arpsolutions.ai" }, { lbl: "Ventas empresariales", val: "sales@arpsolutions.ai" }, { lbl: "Empleo", val: "careers@arpsolutions.ai" }],
      services: ["Automatización de Flujos IA", "Analítica Predictiva", "IA Conversacional", "Integraciones API", "Consulta general"],
      founderPhone: "Teléfono",
    },
    footer: {
      ctaEyebrow: "Construyamos juntos", ctaTitle: "¿Listo para desplegar tu", ctaAccent: "ecosistema IA?",
      ctaDesc: "Reserva una llamada gratuita con Justin, Alexander o Adrian — y obtén una hoja de ruta de IA clara para tu empresa.",
      ctaBtn1: "Reservar una llamada", ctaBtn2: "Explorar nuestros servicios →",
      brandDesc: "Ecosistemas de Automatización IA Empresarial. Fundado por Justin Kuijper, Alexander Janssen y Adrian Alvarez.",
      newsletter: "Mantente informado", nlPh: "tu@empresa.com", nlBtn: "Suscribirse", nlSuccess: "Suscrito. ¡Bienvenido!",
      colSolutions: "Soluciones", colNavigate: "Navegar", colLegal: "Legal",
      navLinks: ["Inicio", "Soluciones", "Cómo funciona", "Contacto"],
      legalLinks: ["Política de privacidad", "Términos de servicio", "Política de cookies", "Seguridad"],
      rights: "Todos los derechos reservados.", status: "Todos los sistemas operativos",
    },
  },

  nl: {
    nav: { solutions: "Oplossingen", howItWorks: "Hoe het werkt", contact: "Contact", signIn: "Inloggen", getStarted: "Aan de slag" },
    hero: {
      badge: "Enterprise AI-Automatisering",
      line1: "Uw AI-partner", line2: "voor het volgende", line2accent: "decennium",
      description: "ARP Solutions helpt ondernemingen operationele complexiteit te elimineren via AI-gestuurde automatiseringsecosystemen — zodat uw team zich op groei kan focussen.",
      cta1: "Aan de slag", cta2: "Bekijk demo",
      stat1val: "Bewezen ROI", stat1lbl: "Bij elk project",
      stat2val: "Enorm", stat2lbl: "Uren bespaard per maand",
      dashTitle: "AI-motor actief", dashLive: "Live", dashChart: "Wekelijkse prestaties",
      dashSaved: "Bespaard", dashAcc: "Nauwkeurigheid", dashUp: "Uptime",
      notifTitle: "Nieuwe gekwalificeerde lead", notifSub: "2 minuten geleden · Geautomatiseerd",
    },
    services: {
      badge: "Wat we doen",
      title: "Alles wat uw onderneming nodig heeft", titleAccent: "om te schalen met AI",
      subtitle: "Van uw eerste automatisering tot een volledig geïntegreerd AI-ecosysteem — gebouwd voor ondernemingen die niet stilstaan.",
      learnMore: "Meer weten",
      items: [
        { tag: "Procesautomatisering", title: "AI-werkstroomautomatisering", desc: "Elimineer handmatige knelpunten met end-to-end procesautomatisering via intelligente AI-agenten.", feats: ["Autonome AI-agenten 24/7", "Volledige procesdekking", "Geen verstoring van bestaande operaties"], metric: { val: "Enorm", lbl: "vermindering handmatige werklast" } },
        { tag: "Data-intelligentie", title: "Voorspellende analyse", desc: "Transformeer bedrijfsdata in strategisch concurrentievoordeel met voorspellende modellen die patronen blootleggen.", feats: ["Realtime dashboards", "Proactieve anomaliewaarschuwingen", "Aangepaste prognosemodellen"], metric: { val: "[X]×", lbl: "verbetering prognoseresultaten" } },
        { tag: "Klantervaring", title: "Conversationele AI", desc: "Implementeer chatbots en AI-spraakagenten voor inkomende gesprekken, leadkwalificatie en ticketoplossing.", feats: ["AI-spraakagenten voor telefoongesprekken", "Intelligente escalatie", "Omnichannel-inzet"], metric: { val: "[X]%", lbl: "vragen autonoom afgehandeld" } },
        { tag: "Infrastructuur", title: "API-integraties", desc: "Verbind AI naadloos met uw bestaande technologiestapel — CRM, ERP, HRIS en eigen databases met enterprise-beveiliging.", feats: ["REST & GraphQL API-ondersteuning", "SSO & RBAC-beveiliging", "99,9% uptime SLA"], metric: { val: "Snel", lbl: "tijd tot integratie" } },
      ],
      ctaEyebrow: "Klaar om uw operaties te transformeren?", ctaTitle: "Begin met automatiseren.", ctaAccent: "Schaal zonder grenzen.", ctaBtn1: "Praat met ons team", ctaBtn2: "Bekijk een live demo",
    },
    hiw: {
      badge: "Ons proces", title: "Van eerste kennismaking tot", titleAccent: "live AI-systemen",
      subtitle: "Een bewezen vierfasenmethodologie — van operationele audit tot volledig geïmplementeerd AI-ecosysteem zonder verstoring.",
      steps: [
        { phase: "Ontdekking",    title: "We auditeren uw operaties",      desc: "Ons team voert een grondige audit uit van uw werkstromen, technologiestapel en pijnpunten.", bullets: ["Huidige situatie in kaart brengen", "Beoordeling technologiestapel", "Automatiseringskansen scoren"] },
        { phase: "Architectuur", title: "We ontwerpen uw AI-ecosysteem",   desc: "We bouwen een op maat gemaakt AI-ecosysteem — geen kant-en-klare sjablonen.", bullets: ["Aangepaste AI-agentarchitectuur", "End-to-end integratieblauwdruk", "Gefaseerde uitrolroadmap"] },
        { phase: "Implementatie", title: "We bouwen en integreren",         desc: "Onze engineers implementeren uw AI-werkstromen met grondige testcycli voordat alles live gaat.", bullets: ["Veilige API-integratie", "Parallelle testomgeving", "Implementatie zonder downtime"] },
        { phase: "Optimalisatie", title: "We monitoren en verbeteren",      desc: "Na de lancering bewaken systemen continu de prestaties, markeren anomalieën en optimaliseren automatisch.", bullets: ["Realtime prestatiebewaking", "Continue modelhertraining", "Toegewijd succesbegeleiding"] },
      ],
      trust: [
        { val: "Weken, geen maanden", lbl: "Gemiddelde tijd tot eerste implementatie" },
        { val: "Nul downtime",        lbl: "Gegarandeerde implementatiemethode" },
        { val: "Continue ROI",        lbl: "Post-lanceringsoptimalisatie inbegrepen" },
      ],
    },
    contact: {
      badge: "Neem contact op", title: "Laten we uw", titleAccent: "AI-ecosysteem bouwen",
      subtitle: "Neem rechtstreeks contact op met een van onze oprichters, of vul het formulier in en we reageren binnen één werkdag.",
      founders: "Neem contact op met een oprichter",
      formTitle: "Stuur ons een bericht", formDesc: "Vertel ons over uw project en we stellen binnen 24 uur een voorstel op maat voor.",
      name: "Volledige naam", email: "Zakelijk e-mailadres", company: "Bedrijf", service: "Dienst van interesse", message: "Bericht",
      namePh: "Jan de Vries", emailPh: "jan@bedrijf.nl", companyPh: "Mijn Bedrijf", servicePh: "Selecteer een dienst…", messagePh: "Vertel ons over uw project en huidige uitdagingen…",
      submit: "Bericht verzenden", sending: "Verzenden…",
      privacy: "We reageren doorgaans binnen 1 werkdag. Uw gegevens worden nooit gedeeld.",
      successTitle: "Bericht verzonden!", successDesc: "Bedankt voor uw bericht. Een oprichter van ARP Solutions neemt binnen één werkdag contact op.", successBtn: "Nog een bericht sturen",
      errorMsg: "Er is iets misgegaan. Probeer het opnieuw of stuur ons een e-mail.",
      emails: [{ lbl: "Algemene vragen", val: "hello@arpsolutions.ai" }, { lbl: "Zakelijke verkoop", val: "sales@arpsolutions.ai" }, { lbl: "Vacatures", val: "careers@arpsolutions.ai" }],
      services: ["AI-werkstroomautomatisering", "Voorspellende analyse", "Conversationele AI", "API-integraties", "Algemene vraag"],
      founderPhone: "Telefoon",
    },
    footer: {
      ctaEyebrow: "Laten we samen bouwen", ctaTitle: "Klaar om uw", ctaAccent: "AI-ecosysteem te implementeren?",
      ctaDesc: "Boek een gratis ontdekkingsgesprek met Justin, Alexander of Adrian — en vertrek met een duidelijke AI-routekaart.",
      ctaBtn1: "Boek een gesprek", ctaBtn2: "Bekijk onze diensten →",
      brandDesc: "Enterprise AI-automatiseringsecosystemen. Opgericht door Justin Kuijper, Alexander Janssen en Adrian Alvarez.",
      newsletter: "Blijf op de hoogte", nlPh: "uw@bedrijf.nl", nlBtn: "Abonneren", nlSuccess: "U bent geabonneerd. Welkom!",
      colSolutions: "Oplossingen", colNavigate: "Navigeren", colLegal: "Juridisch",
      navLinks: ["Home", "Oplossingen", "Hoe het werkt", "Contact"],
      legalLinks: ["Privacybeleid", "Servicevoorwaarden", "Cookiebeleid", "Beveiliging"],
      rights: "Alle rechten voorbehouden.", status: "Alle systemen operationeel",
    },
  },
};